services:
  redis:
    image: redis:7-alpine
    container_name: lunchbox-redis
    ports:
      - "6379:6379"

  menu-service:
    build:
      context: .
      dockerfile: services/menu-service/Dockerfile
    container_name: lunchbox-menu-service
    ports:
      - "3001:3001"

  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: lunchbox-order-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ORDER_DB_FILE: /data/orders.json
    volumes:
      - ./data:/data
    depends_on:
      - redis
    ports:
      - "3002:3002"

  worker-service:
    build:
      context: .
      dockerfile: services/worker-service/Dockerfile
    container_name: lunchbox-worker-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ORDER_SERVICE_INTERNAL_URL: http://order-service:3002
    depends_on:
      - redis
      - order-service

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: lunchbox-auth-service
    environment:
      AUTH_DB_FILE: /data/auth.sqlite
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER}
      OTP_DEBUG_MODE: ${OTP_DEBUG_MODE:-1}
    volumes:
      - ./data:/data
    ports:
      - "3003:3003"

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: lunchbox-api-gateway
    environment:
      MENU_SERVICE_URL: http://menu-service:3001
      ORDER_SERVICE_URL: http://order-service:3002
      AUTH_SERVICE_URL: http://auth-service:3003
    depends_on:
      - menu-service
      - order-service
      - auth-service
    ports:
      - "3000:3000"
