bug:
  - changed-files:
    - any-glob-to-any-file:
      - 'Frontend/lunchbox-app/src/app/features/**/*.ts'
      - 'ZIPTen/nodejs-monorepo/src/**/*.js'
      - 'Backend/**/*.js'

enhancement:
  - changed-files:
    - any-glob-to-any-file:
      - added-files: '**/*.ts'
      - added-files: '**/*.js'
      - added-files: '**/*.component.ts'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'DEPLOYMENT*.md'
      - '**/*.txt'

chore:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'angular.json'
      - '.github/**'
      - '*.yaml'
      - '*.yml'
